name: RingsReworked
version: 1.0
authors:
  - LuckyMutt
api-version: 1.19
description: Rework of the plugin Rings by the user lilsimmi
main: me.luckymutt.rw.RingsReworked

commands:
  rings:
    description: The main command for the rings plugin
    usage: /rings

permissions:
  rings.*:
    description: Base permission for the plugin
    children:
      rings.use.*:
        description: Base permission for using the rings
      rings.craft.*:
        description: Base permission for crafting the rings
      rings.command.*:
        description: Base permission for using the commands
        children:
          rings.command.gui: true
          rings.command.list: true
          rings.command.recipe: true
          rings.command.give: true
